### ISSUE TITLE
GREASE Registration Strength

### ISSUE THREAD

**Issue by gamagori** [target/grease#1]
# GREASE: Registration Bug
###### USE THIS TEMPLATE FOR YOUR ISSUE!

  * Primary Contact: [Grant Gordon](grant.gordon@target.com)
  * Team: Target
  
### Abstract

Registration of nodes to the database _should_ happen before anything else but we are still _very_ exposed to potential SegFault since in the cases listed below we could be "unregistered". We should implement more robust and centralized registration checking/error checking

### Supporting Elements

  * GREASE skips registration when an ID file is already there, without verifying with the DB:
https://github.com/target/grease/blob/master/tgt_grease_enterprise/LaunchCtl.py#L66-L72
  * GREASE attempts to report Telemetry, without making sure that ```self._grease_identity``` is in the database. 
https://github.com/target/grease/blob/master/tgt_grease_core_util/Telemetry.py#L35-L51
  * I could tear down and rebuild the Dockerized GREASE database, but the server ID file on my local computer remained. So, when I went to register again, GREASE skipped the registration because I already had an ID file, and bailed when trying to report metrics.

### Issue Checklist

  - [x] Maintainer has viewed
  - [x] Loaded into Backlog
  - [ ] PR Submitted [Link Here](Eventual Link)

**Comment by lemoney** [comment]
@gamagori can we close this with the 1.2 release now?

**Comment by gamagori** [comment]
Closing this - it's in the 2.0.0 branch.
