### ISSUE TITLE
Typo Causes kill-server Failures

### ISSUE THREAD

**Issue by gamagori** [target/grease#31]
# Typo Causes kill-server Failures
###### USE THIS TEMPLATE FOR YOUR ISSUE!

  * Primary Contact: Grant
  * Team: Independent
  
### Abstract

A typo in a SQL statement causes kill-server to fail from the command line. 

### Supporting Elements

https://github.com/target/grease/blob/7a387b6404acce22bd35c9af9714150605bf2786/tgt_grease_enterprise/Article14Section31.py#L157

https://gist.github.com/gamagori/99490bec609b3c053539a22b015087be

### Issue Checklist

  - [ ] Maintainer has viewed
  - [ ] Loaded into Backlog
  - [ ] PR Submitted [Link Here](Eventual Link)

**Comment by lemoney** [comment]
fixed in #33
