### ISSUE TITLE
URL Source

### ISSUE THREAD

**Issue by gamagori** [target/grease#33]
# URL Source
###### USE THIS TEMPLATE FOR YOUR ISSUE!

  * Primary Contact: [Grant Gordon](grant.mattke.gordon@gmail.com)
  * Team: Independent
  
### Abstract

Create GREASE's first open-source Source to serve as an example for people who want to create their own source. This Source will allow GREASE to consume hosts and API endpoints as data sources.

### Supporting Elements

Capabilities:
  * Ping hostnames
  * Ping IP address, by array or by subnet
  * Other TBD, pending conversation with James tomorrow. 

Assorted To-Do:
  * Move BaseSourceClass to the Sources folder, like the BaseDetectorClass
  * Provide a sample config. Maybe ensure localhost is online? 
  * Add logging to DetectorConfiguration.py to ensure people without configs to reference can understand what's going on. 

### Issue Checklist

  - [x] Maintainer has viewed
  - [x] Loaded into Backlog
  - [ ] PR Submitted [Link Here](Eventual Link)

**Comment by lemoney** [comment]
Included in release v2
