### ISSUE TITLE
Notifier needs to use Config

### ISSUE THREAD

**Issue by gamagori** [target/grease#57]
# GREASE Issue Template Update Notifier to use Configuration 
###### USE THIS TEMPLATE FOR YOUR ISSUE!

  * Primary Contact: [Grant Gordon](gmgordon@postholdings.com)
  * Team: Bad Grammar and the Solo Queue
  
### Abstract

Notifier still uses self._hipchat* for config values rather than using the config object 

### Issue Checklist

  - [ ] Maintainer has viewed
  - [ ] Loaded into Backlog
  - [ ] PR Submitted [Link Here](Eventual Link)

**Comment by gamagori** [comment]
@lemoney remind me to do this tomorrow lol

**Comment by gamagori** [comment]
This isn't necessary - the way Notifier is coded now makes sense (allows the user to override the default room if they want).

**Comment by lemoney** [comment]
@gamagori _very nice_ that's what we we're hoping for!
